name: build-and-cache
on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * *'
  push:
jobs:
  build-and-cache:
    runs-on: buildjet-16vcpu-ubuntu-2204-arm
    env:
      NIXPKGS_ALLOW_UNFREE: 1
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v22
    - uses: cachix/cachix-action@v12
      with:
        name: mongoarm64
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Update flake.lock
      run: |
        nix flake update
    - name: Build flake
      run: nix build --impure